### ISSUE TITLE
if comma (,) isn't encoded in the URL, Authentication fails

### ISSUE THREAD

**Issue by girishrd2004** [gevorg/http-auth#45]
Hi @gevorg 

I have observed an issue which passing a JSON object as request parameter to http server. When the comma isn't encoded, the auth fails!

Example: Running https://github.com/gevorg/http-auth/blob/master/examples/digest.js

http://127.0.0.1:1337/asd?test="sa,Casd" - Fails to authenticate
http://127.0.0.1:1337/asd?test="sa%2CCasd" - Succeed to authenticate

I am not sure if this is an issue, but I expect the URL to work even without encoding for comma...

**Comment by gevorg** [comment]
Hi @girishrd2004 

Thanks for telling me. The reason behind is that comma and few other characters are used in HTTP to build request / response data. For that reason it is always good practice to encode URI parameters, else you might get random problems with your requests / responses. Gevorg
