### ISSUE TITLE
package.json locked versioning

### ISSUE THREAD

**Issue by frozencemetery** [gevorg/http-auth#46]
I am in the process of packaging http-auth for Fedora.  In package.json, your dependencies are on exact versions of libraries; where possible, it's generally better to specify ranges instead (e.g., "^1.8.0" instead of "1.8.0" using [semver](https://docs.npmjs.com/misc/semver)).  I wanted to alert you that I'll be changing the flat versions to caret versions in the course of packaging, unless you think something different should be done.

Thanks!

**Comment by gevorg** [comment]
Hello Robbie, sure that would be better, let me know if you need my help. Thank You! Gevorg

**Comment by gevorg** [comment]
Closing this item for now, please open pull request when you will be ready. Thank You!
