### ISSUE TITLE
How to do HTTP and HTTPS simultaneously?

### ISSUE THREAD

**Issue by escribileamauro** [gevorg/http-auth#50]
Hi Gevorg,

I've been having some issues including both HTTP and HTTPS in the same server.  I have set up a transparent proxy that just passes through all requests, but when I include the basic authentication it stops working. How should I do it?  Here's the code I am using:

var auth = require('http-auth');
var http = require('http');
var net = require('net');

var basic = auth.basic({
    realm: "Access area",
    file: __dirname + "/users"
});

var server = http.createServer(function(request, response) {
    var options = {
        'hostname':  request.headers.host,
        'path' : request.url,
        'method':request.method,
        'headers': request.headers
    };

    var proxy = http.request(options,function(proxy_response){
        proxy_response.on('data', function (chunk) {
            response.write(chunk);
        });
        proxy_response.on('end', function() {
            response.end();

        });
        response.writeHead(proxy_response.statusCode, proxy_response.headers);
    });

    proxy.on('error', function(e) {
        console.log('problem with request: ' + e.message);
    });

    proxy.end();
}).listen(8888);

server.addListener('connect', function ( request, socketRequest, bodyhead ) {

            var proxySocket = new net.Socket();
            proxySocket.connect(/[^:]+$/.exec(request.url)[0],/[^:]+/.exec(request.url)[0],function () {
                    proxySocket.write( bodyhead );
                    socketRequest.write( "HTTP/" + request.httpVersion + " 200 Connection established\r\n\r\n" );
                }
            );
            proxySocket.on('data', function (chunk) {
                socketRequest.write(chunk, 'binary');
            });

            proxySocket.on('end', function() {
                socketRequest.end();
            });

            proxySocket.on('error', function(e) {
                console.log('problem with request: ' + e.message);
            });

            socketRequest.on('data', function (chunk) {
                proxySocket.write(chunk, 'binary');
            });
            socketRequest.on('end', function() {
                proxySocket.end();
            });

            socketRequest.on('error', function(e) {
                console.log('problem with request: ' + e.message);
            });
    }
);

Thank you!

**Comment by gevorg** [comment]
The only thing that I can suggest is to use http-proxy library, you can find integration guide here: https://github.com/gevorg/http-auth#http-proxy-integration
