### ISSUE TITLE
Exclude http-auth from specific route

### ISSUE THREAD

**Issue by ninjaprox** [gevorg/http-auth#51]
I try to exclude `http-auth` for specific route. Here is the code.

```javascript
var auth = require('http-auth');
var basic = auth.basic({
    realm: "MyApp",
    file: __dirname + "/config/auth.basic"
});

app.use(function(req, res, next) {
    if ('/specific/path' === req.path) {
        next();

        return;
    }
    return auth.connect(basic);
});
```

However, when I hit `/specific/path`, got `{ "message": "auth.connect is not a function", "error": {}}`. Anything I am doing wrong?

**Comment by gevorg** [comment]
I think you can try following solution:

auth.connect(basic) returns function so you can use something like return (auth.connect(basic))(req,res,next);

**Comment by ninjaprox** [comment]
I tried that also, but it doesn't work.

**Comment by gevorg** [comment]
This works for me:

https://gist.github.com/gevorg/7168d5f02c1ca5362b2a

**Comment by ninjaprox** [comment]
Thanks :+1:
