### ISSUE TITLE
NPM dependency error on linux

### ISSUE THREAD

**Issue by Ninetainedo** [gevorg/http-auth#53]
Hello,

I am using this module for my personal website and I encountered an error while setting it up for Linux.
It works pretty fine on Windows but doesn't even install on my Debian 7 dedicated server.
Here is a pastebin of the error : http://pastebin.com/kH1ufqEP

**Comment by gevorg** [comment]
Hi,

Is it possible to update Node to latest stable version? Seems your machine is using v0.10.10 and there is dependency conflict for that version. Gevorg

**Comment by Ninetainedo** [comment]
Ok, that fixed the issue, thank you very much.
Have a nice day!
