### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by LaKing** [gevorg/http-auth#54]
Great work. the only thing I couldnt figure out so far, is how to get the authenticated username in socket.io, ...

Do you have any hints maybe?

**Comment by gevorg** [comment]
Thanks, I think you need to get HTTP request object somehow and read user property, however not sure how. Will be able to look into this on Monday.

**Comment by LaKing** [comment]
I found a solution. Maybe worth to mention in the readme, ... ?

`var getUserName = function(socket) {

    if (!socket.handshake.headers.authorization) return;
    if (socket.handshake.headers.authorization.search('Basic ') !== 0) return;
    var auth = new Buffer(socket.handshake.headers.authorization.split(' ')[1], 'base64').toString().split(":");
    return auth.shift();

};`

**Comment by gevorg** [comment]
Yes, that would do too.
